config/routes.rb
Rails.application.routes.draw do

  root to: "vehicles#index"
  # I'd like to change this
  
  resources :vehicles

  devise_for :customers
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :vehicles
  # may need to change that
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
	validates :make, presence: true
    validates :model, presence: true
    validates :year, presence: true,
                    	length: { is: 4 }
    validates :VIN, presence: true   
    validates :color, presence: true

    belongs_to :customer
    #may need to change that             	                	                	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy, :authorize_customer]

  # Only allow authenticated users to access these actions
  before_action :authenticate_customer!
  # may need to change that

  # Only allow authorized users to access these actions
  before_action :authorize_customer, only: [:show, :edit, :update, :destroy]
  # may need to change that

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.where(customer: current_customer)
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    # same as doing @vehicle.customer_id = current_customer.id
    @vehicle.customer = current_customer

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:make, :model, :year, :VIN, :color)
    end

    def authorize_customer
      unless @vehicle.customer == current_customer
        redirect_to vehicles_url, notice: 'You may not view or update a vehicle that is not yours.'
      end
    end
    # may need to change that

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InsureCo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      body {
        background: darkblue;
        color: lightgrey;
        font-family: "Comic Sans MS", cursive, sans-serif;
      }

      /*a {
        font-family: "Comic Sans MS", cursive, sans-serif;
      }*/
    </style>

  </head>

  <body>

  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if current_customer %>
      <%= link_to "Sign Out", destroy_customer_session_path, method: :delete %> | 
      <%= link_to "Edit Account", edit_customer_registration_path %>
    <% else %>
      <%= link_to "Sign In", new_customer_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :make %>
    <%= form.text_field :make, id: :vehicle_make %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, id: :vehicle_model %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :vehicle_year %>
  </div>

  <div class="field">
    <%= form.label :VIN %>
    <%= form.text_field :VIN, id: :vehicle_VIN %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.select :color, options_for_select(['red', 'orange', 'yellow', 'green', 'blue', 'purple', 'pink', 'brown', 'black', 'grey', 'white', 'other']), id: :vehicle_color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>VIN</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.make %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.year %></td>
        <td><%= vehicle.VIN %></td>
        <td><%= vehicle.color %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <% if vehicle.customer == current_customer %>
          <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
          <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <!-- may need to change that -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @vehicle.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @vehicle.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @vehicle.year %>
</p>

<p>
  <strong>VIN:</strong>
  <%= @vehicle.VIN %>
</p>

<p>
  <strong>Color:</strong>
  <%= @vehicle.color %>
</p>

<% if @vehicle.customer == current_customer %>
	<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<% end %>
<%= link_to 'Back', vehicles_path %>